### ISSUE TITLE
Egzamin 

### ISSUE THREAD

**Issue by Rendianor** [pjastr/WizualizacjaDanychStac#1]
Dzień dobry,
Mam pytanie dotyczące egzaminu. Czy pojawi się jakiś egzamin przykładowy z Wizualizacji Danych?

**Comment by pjastr** [comment]
Dzień dobry.

Przykładowy egzamin jest już od ostatniego wykładu na stronie http://wmii.uwm.edu.pl/~piojas/index.php/2019/06/03/zasady-egzaminu-wds/ - dokładny link http://wmii.uwm.edu.pl/~piojas/wp-content/uploads/2019/06/Egz1.zip 

Jeśli potrzebuje Pan więcej przykładowych zestawów, to też mogę coś przygotować.

**Comment by Rendianor** [comment]
Nie zauważyłem, jeżeli to dla Pana nie problem to bym prosił o więcej przykładowych zestawów.
Dziękuje bardzo.

**Comment by pjastr** [comment]
To za kilka chwil coś przygotuję i umieszczę na tej samej stronie co wyżej (również dla innych).

**Comment by Rendianor** [comment]
Dobrze, dziękuje.

**Comment by pjastr** [comment]
Wrzuciłem dziś nowe 3 przykładowe zestawy. Ogólnie aby dostać 3 z egzaminu trzeba zrobić część z samym postaw Pythona lub jeden wykres i trochę z pythona.
